services:
  pxe:
    container_name: pxe
    build:
      context: ./
    cap_add:
      - NET_ADMIN
    network_mode: 'host'
    ports:
      - '67:67/udp'
      - '68:68/udp'
      - '69:69/udp'
      - '8067:8067/tcp'
    environment:
      - 'PXE_PASSWORD=${PXE_PASSWORD:-password}'
      - 'PXE_SERVERIP=${PXE_SERVERIP:-192.168.1.10}'
      - 'PXE_ROUTERIP=${PXE_ROUTERIP:-192.168.1.1}'
    volumes:
      - '${PXE_DATAPATH:-./pxe}:/userdata'
    restart: unless-stopped

